version: '3.8'

services:
    http_api:
        image: snisioi/retele:2021
        volumes:
            - .:/elocal
        tty: true
        ports:
         - "8001:8001" # schimbati-le in functie de portul pe care il doriti deschis
        #command: bash -c "python3 /elocal/simple_flask.py"